name: Deploy Frontend
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t jayant/react-frontend -f Dockerfile.dev 
      - run: docker run -e CI=true jayant/react-frontend npm run test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: jayant/beanstallk-deploy@v18 
        with: 
          aws_access_key: ${{ screts.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: elastic-beanstalk-docker-testing
          environment_name: Elastic-beanstalk-docker-testing-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-2-229025720843
          region: ap-southeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip 